use_frameworks!

platform :ios, '9.0'

target 'HDLNetworkAccessor_Example' do
  pod 'HDLNetworkAccessor', :path => '../'

  target 'HDLNetworkAccessor_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
